### ISSUE TITLE
Can't run rails server/rake task after instaling gem

### ISSUE THREAD

**Issue by cupnoodle** [omniauth/omniauth#879] opened 2017-02-11 13:03 UTC
There's seems to be an error whenever I type "rails s" or any rake command after installing this gem.

Rails version : 4.2.6
Ruby version : 2.3.0
The error is here 
<img width="1088" alt="screen shot 2017-02-11 at 9 01 09 pm" src="https://cloud.githubusercontent.com/assets/3954625/22853934/5a0a89fa-f09d-11e6-8db2-5e959ebbbe9f.png">

[Full error log here](http://pastebin.com/4J5fUvWr)

**Comment by britg** [comment] 2017-02-11 17:09
I'm running into the same issue. It looks to be related to this PR: https://github.com/omniauth/omniauth/pull/874

I will attempt a fix, but I am not familiar with the code base.

**Comment by tmilewski** [comment] 2017-02-11 20:10
@britg Would you mind providing some more information? Is your issue also when using the `omniauth-facebook` gem?

**Comment by britg** [comment] 2017-02-13 14:28
@tmilewski Yes, the issue was occurring with `omniauth-facebook` and any other `omniauth-flavor` gem. It turns out explicitly upgrading the `hashie` gem to 3.5.3 fixed the issue for me. 

I believe the error was related to this fix: https://github.com/intridea/hashie/commit/c269a1cc98c69848bd490f5024d884775061df6f

Here's a simple starter Rails project that reproduces the issue with hashie 3.5.2 https://github.com/britg/OmniauthHashieRepro

**Comment by britg** [comment] 2017-02-13 14:30
And here's the stack trace:

OmniauthDebug git:(upstream ⚡ master) rails c
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'omniauth-google-oauth2'.
Gem Load Error is: private method `warn' called for nil:NilClass
Backtrace for gem load error is:
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:334:in `log_built_in_message'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:139:in `custom_writer'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:207:in `block in deep_update'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `each_pair'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `deep_update'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:115:in `initialize'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth/auth_hash.rb:24:in `new'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth/auth_hash.rb:24:in `regular_writer'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:140:in `custom_writer'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:207:in `block in deep_update'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `each_pair'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `deep_update'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/hashie-3.5.2/lib/hashie/mash.rb:115:in `initialize'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth.rb:45:in `new'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth.rb:45:in `defaults'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth.rb:50:in `initialize'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/singleton.rb:142:in `new'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/singleton.rb:140:in `instance'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-1.5.0/lib/omniauth.rb:119:in `config'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:127:in `<top (required)>'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/strategies/google_oauth2.rb:3:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/strategies/google_oauth2.rb:3:in `<top (required)>'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/google_oauth2.rb:1:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/google_oauth2.rb:1:in `<top (required)>'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth-google-oauth2.rb:1:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/omniauth-google-oauth2-0.4.1/lib/omniauth-google-oauth2.rb:1:in `<top (required)>'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
/Users/Eezo/Projects/OmniauthDebug/config/application.rb:7:in `<top (required)>'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
/Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
	from /Users/Eezo/Projects/OmniauthDebug/config/application.rb:7:in `<top (required)>'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /Users/Eezo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Eezo/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by tmilewski** [comment] 2017-02-13 16:10
This should be fixed in `1.5.0`. Thanks!

**Closed by tmilewski** 2017-02-13 16:10 UTC
