### ISSUE TITLE
Installing hashie 3.5.1 yields an OmniAuth warning

### ISSUE THREAD

**Issue by retorquere** [omniauth/omniauth#873] opened 2017-02-02 19:33 UTC
When I start up my sinatra app with OmniAuth 1.3.2 and hashie 3.5.1, I get

```
WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /Users/emile/.rvm/gems/ruby-2.3.0@cvrm/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```

When I downgrade hashie to 3.4.6, Sinatra starts up without any warnings.

**Comment by tmilewski** [comment] 2017-02-02 23:02
Duplicate of #872. Please refer to the conversation there.

**Closed by tmilewski** 2017-02-02 23:02 UTC
